[issues]
exclude = [
  # goconst: Ignore for example/test data
  'string `(foo|bar|baz|qux|true|false|example|exit \d|mytask|OPTION_VAR)` has \d+ occurrences',
  # golint: false positives for multi-file packages
  'should have a package comment',
  # gosec: Duplicate of errcheck
  'G104: Errors unhandled',
  # gosec: Allow file inclusions
  'G304: Potential file inclusion via variable',
]
exclude-use-default = false

[linters]
enable-all = true
disable = [
  "gochecknoglobals", # There are valid use cases for globals
  "maligned",         # Readability is more important than saving bytes
  "scopelint",        # False positives in tests: https://github.com/kyoh86/scopelint/issues/4
]

[linters-settings]

  [linters-settings.goconst]
  min-len = 0
  min-occurrences = 3

  [linters-settings.gocyclo]
  min-complexity = 10

  [linters-settings.golint]
  min-confidence = 0.0

  [linters-settings.govet]
  check-shadowing = true

  [linters-settings.misspell]
  locale = "US"

  [linters-settings.nakedret]
  max-func-lines = 0
