version: "2"
issues:
  max-same-issues: 0

linters:
  enable:
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exptostd
    - fatcontext
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gosec
    - intrange
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
  settings:
    errcheck:
      exclude-functions:
        # We're only ever writing to stdout/stderr (outside of tests)
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
    gocognit:
      min-complexity: 10
    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine
        - ptrToRefParam
        - whyNoLint
    gosec:
      excludes:
        - G104 # duplicate of errcheck
        - G304 # include files from variables on purpose
        - G307 # duplicate of errcheck
    govet:
      enable-all: true
      disable:
        - fieldalignment
    lll:
      line-length: 100
      tab-width: 2
    misspell:
      locale: US
    nakedret:
      max-func-lines: 0
    revive:
      confidence: 0
  exclusions:
    rules:
      - linters: [revive]
        text: package-comments
      - linters:
          - gocognit
          - gosec
        path: _test\.go

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
