[issues]
exclude = [
  # goconst: Ignore for example/test data
  'string `(foo|bar|baz|qux|true|false|example|exit \d|mytask|OPTION_VAR)` has \d+ occurrences',
  # golint: false positives for multi-file packages
  'should have a package comment',
  # gosec: Duplicate of errcheck
  'G104: Errors unhandled',
  # gosec: Allow file inclusions
  'G304: Potential file inclusion via variable',
]
exclude-use-default = false

[linters]
enable = [
  "bodyclose",
  "golint",
  "stylecheck",
  "gosec",
  "interfacer",
  "unconvert",
  "dupl",
  "goconst",
  "gocyclo",
  "gocognit",
  "gofmt",
  "goimports",
  "lll",
  "misspell",
  "unparam",
  "nakedret",
  "prealloc",
  "gocritic",
  "gochecknoinits",
  "whitespace",
]

[linters-settings]

  [linters-settings.goconst]
  min-len = 0
  min-occurrences = 3

  [linters-settings.gocognit]
  min-complexity = 15

  [linters-settings.gocyclo]
  min-complexity = 10

  [linters-settings.gofmt]
  simplify = true

  [linters-settings.golint]
  min-confidence = 0.0

  [linters-settings.govet]
  check-shadowing = true

  [linters-settings.misspell]
  locale = "US"

  [linters-settings.nakedret]
  max-func-lines = 0
