site_name: tusk
theme: rtd-dropdown
repo_url: https://github.com/rliebz/tusk

nav:
  - Tusk: index.md
  - The Spec: spec.md
  - Contributing: CONTRIBUTING.md

markdown_extensions:
  - codehilite

extra_css: [pygments.css]
