site_name: tusk
theme: cinder
repo_url: https://github.com/rliebz/tusk
edit_uri: ""

pages:
  - Getting Started: index.md
  - The Spec: spec.md

markdown_extensions:
  - codehilite

extra_css: [pygments.css]
extra_templates: [.circleci/config.yml]
