name: Publish
on:
  push:
    tags: ["v*.*.*"]

jobs:
  release:
    name: Release Dry Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"
      - name: Release Dry Run
        run: |
          header='^## [0-9]+\.[0-9]+\.[0-9]+'
          awk "/${header}/{if(!found){found=1;f=1}else{f=0}} f" CHANGELOG.md |
            go run github.com/goreleaser/goreleaser --release-notes /dev/stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    name: Deploy Docs
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          apt update && apt install -y git
          pip3 install mkdocs==1.3.1
      - name: Deploy
        run: mkdocs gh-deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
