name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Test -trimpath
        run: go test -trimpath -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.59.1

  release:
    name: Release Dry Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.5"
      - name: Release Dry Run
        run: |
          header='^## [0-9]+\.[0-9]+\.[0-9]+'
          awk "/${header}/{if(!found){found=1;f=1}else{f=0}} f" CHANGELOG.md |
            go run github.com/goreleaser/goreleaser --release-notes /dev/stdin --snapshot

  docs:
    name: Docs Dry Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip3 install mkdocs==1.3.1
      - name: Deploy Docs Dry Run
        run: mkdocs build
